CREATE DATABASE Bai2_BT2_QLBH;
USE Bai2_BT2_QLBH;

CREATE TABLE Customer(
cID INT PRIMARY KEY AUTO_INCREMENT,
cNAME VARCHAR(255),
cAGE INT
);
CREATE TABLE Orders(
oID INT AUTO_INCREMENT PRIMARY KEY,
cID INT NOT NULL,
oDATE DATE,
oTotalPrice DOUBLE,
FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE Product(
pID INT AUTO_INCREMENT PRIMARY KEY,
pNAME VARCHAR(200),
pPRICE DOUBLE
);
CREATE TABLE OrderDetail(
oID INT NOT NULL,
pID INT NOT NULL,
odQTY INT NOT NULL,
FOREIGN KEY (oID) REFERENCES Orders(oID),
FOREIGN KEY (pID) REFERENCES Product(pID)
);





